name: Feature Request 🔮
description: Suggest an idea for this project
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Share your idea for this project and we'll consider it for integration.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a specific problem? Please describe
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your suggested solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: Provide example code or implementation details if applicable

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any additional context or screenshots
